apiVersion: synapse.io/v1alpha1
kind: Workflow
metadata:
  name: 'inject-test-1-0'
  namespace: synapse
spec:
  definition:
    id: inject-test
    version: '1.0'
    name: Inject Test Workflow
    description: Injects Hello World into state data
    start: inject
    states:
      - name: inject
        type: inject
        data:
          id: 1
          category:
            id: 0
            name: mammals
          name: doggie
          photoUrls:
            - string
          tags:
            - id: 0
              name: dog
          status: available
        end: true
status: {}