apiVersion: synapse.io/v1alpha1
kind: Trigger
metadata:
  generateName: trigger-
  namespace: synapse
spec:
  conditions:
    - name: condition1
      filters:
        - name: testevent1
          contextAttributes:
            - key: type
              value: io.synapse.test
            - key: source
              value: mytestsource
            - key: correlationId
  outcome:
    type: RUN
    workflow:
      id: singleoperation
      version: latest