apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-correlator-0
  namespace: synapse
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
spec:
  selector:
    matchLabels:
      app: synapse-correlator
  template:
    metadata:
      labels:
        app: synapse-correlator
        version: '0.1.0'
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
    spec:
      containers:
      - name: synapse-correlator
        image: synapse/correlator:0.1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

---

apiVersion: v1
kind: Service
metadata:
  name: synapse-correlator
  namespace: synapse
  labels: 
    app: synapse-correlator
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: synapse-correlator