global using Microsoft.AspNetCore.JsonPatch;
global using Neuroglia;
global using Neuroglia.Serialization;
global using ServerlessWorkflow.Sdk.Models;
global using Synapse.Integration.Models;
global using System;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Runtime.Serialization;
global using Error = Synapse.Integration.Models.Error;