title: Synapse
email: cncf.serverless.workflow@gmail.com
description: >-
  Serverless Workflow Management System
baseurl: "/synapse"
url: "https://serverlessworkflow.github.io"
twitter_username: synapse_wfms
github_username:  serverlessworkflow

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-remote-theme
