global using Grpc.Net.Client;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Neuroglia;
global using Neuroglia.Serialization;
global using ProtoBuf;
global using ProtoBuf.Grpc;
global using ProtoBuf.Grpc.Client;
global using ServerlessWorkflow.Sdk.Models;
global using System.Runtime.Serialization;
global using System.ServiceModel;
global using Error = Synapse.Integration.Models.Error;
