global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Neuroglia;
global using Neuroglia.Serialization;
global using ServerlessWorkflow.Sdk;
global using ServerlessWorkflow.Sdk.Models;
global using Synapse.Integration.Models;
global using Synapse.Runtime.Executor.Configuration;
global using Synapse.Runtime.Services;